version: '3.9'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
      args:
        - APP_ENV=development
    working_dir: /opt/src/app
    volumes:
      - .:/opt/src/app
    ports:
      - 8080:80
      - 9001:9001