version: '3.9'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /go/src
    volumes:
      - .:/go/src
    ports:
      - 8080:80
    command: tail -f "/dev/null"